aws:
    build: .
    container_name: "aws"
    net: "host"
    environment:
        AWS_ACCESS_KEY_ID: OVERRIDE ME 
        AWS_SECRET_ACCESS_KEY: OVERRIDE_ME
        AWS_REGION: us-west-2
    user: 1000:1000
    command: help
